### ISSUE TITLE
How to find out semver for firmwares?

### ISSUE THREAD

**Issue by pambardekar** [NordicSemiconductor/nrf-device-setup-js#44]
I am trying out nrf-device-setup to upgrade 52840 dongle to desired soft device version. I am not able to figure out what semver string to use for different softdevice versions. Is there any documentation for this?

**Comment by bencefr** [comment]
Hi @pambardekar , sorry for the late answer.

_semver_ is a string contained in the application image and is not related to SoftDevice. However an application might use or require a SoftDevice, in which case you'll need its ID.

The list of SoftDevice IDs is easiest to find here: https://github.com/NordicSemiconductor/pc-nrfutil/#usage

**Comment by pambardekar** [comment]
Hi @bencefr 

Thanks for the reply. If I am flashing connectivity firmware along with soft device, is there a way to get semver for the connectivity firmware?

**Comment by bencefr** [comment]
Can I ask where do you get the connectivity firmware from?

As far as I remember there's only one firmware built and released by us: _connectivity_1.2.3_usb_for_s132_3.hex_
 with semver `ble-connectivity 0.1.0+Aug-14-2018-15-12-51`.

This is the pre-compiled hex file that is referred from the released version of _pc-ble-driver-js_ here: https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/master/api/firmwareRegistry.js#L90

However the _semver_ is only used to check if the firmware is already on the device, so if you leave it empty for the first time, _DeviceSetup_ will always perform the DFU. After it is flashed once, you can check the logs/output of your code and look for the _semver_ it reports for the seconds run.

You can try to run your with `DEBUG=*` environment variable set. Ref: [debug](https://www.npmjs.com/package/debug)

**Comment by pambardekar** [comment]
I am trying to compile connectivity firmware for 52840 as per instructions from https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/Installation.md#compiling-the-connectivity-hex-files. I have tried compiling examples/connectivity/ble_connectivity/pca10059/ser_s140_usb_hci from SDK150 and SDK152 both. I used USB patch from pc-ble-driver/hex/sd_api_v6 (branch feature/v6-upgrade) sdk150_connectivity_usb.patch. After using this connectivity firmware (and SD v6) for flashing the dongle, it did not get detected as USB device. I was wondering if semver parameter had anything to do with it.

**Comment by bencefr** [comment]
The _semver_ parameter only prevents to program a device which already has the expected firmware on it, so if you define a wrong or empty _semver_ it will be programmed again.
As for the state of the _sd_api_v6_, it is not yet in master because it is not yet finished. You may be able to get a better answer from @kenr, but the best course of action would be to wait until he can finalize v6, since it has many dependencies that needs to be done first.

**Comment by pambardekar** [comment]
Thanks for the details.
