### ISSUE TITLE
Cannot install latest npm dependency

### ISSUE THREAD

**Issue by ev1stensberg** [NordicSemiconductor/nrf-device-setup-js#45]
Hi! I tried downloading the same example as the one provided in your docs, but failed to do so.. Here's my stack trace

[Terminal.txt](https://github.com/NordicSemiconductor/nrf-device-setup-js/files/2426391/Terminal.txt)

**Comment by bencefr** [comment]
Hi @ev1stensberg ,
Thank you for reporting. The issue roots in https://github.com/NordicSemiconductor/pc-nrfjprog-js which is not yet updated to support nodejs 10.x. We have this on our backlog, and until there's such a version I suggest to use nodejs 8.x LTS.
